name: Renovate
on:
  schedule:
    - cron: "30 1 * * *"

  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        required: false
        default: false
        description: Dry run (don't create PRs)

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: ${{ inputs.dryRun && 'full' || null }}
